In [6]:
import pandas as pd
df=pd.read_csv("data.csv")

In [21]:
df

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2019,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"728,239",ANZSIC06 divisions A-S (excluding classes K633...
1,2019,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"643,809",ANZSIC06 divisions A-S (excluding classes K633...
2,2019,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"62,924",ANZSIC06 divisions A-S (excluding classes K633...
3,2019,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"21,505",ANZSIC06 divisions A-S (excluding classes K633...
4,2019,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"634,710",ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
32440,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32441,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32442,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32443,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
32444,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [22]:
df.head()

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2019,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"728,239",ANZSIC06 divisions A-S (excluding classes K633...
1,2019,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"643,809",ANZSIC06 divisions A-S (excluding classes K633...
2,2019,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"62,924",ANZSIC06 divisions A-S (excluding classes K633...
3,2019,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"21,505",ANZSIC06 divisions A-S (excluding classes K633...
4,2019,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"634,710",ANZSIC06 divisions A-S (excluding classes K633...

In [23]:
df.Year.max()

2019

In [27]:
df.Value.max()

'S'

In [29]:
df.head()

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2019,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"728,239",ANZSIC06 divisions A-S (excluding classes K633...
1,2019,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,"643,809",ANZSIC06 divisions A-S (excluding classes K633...
2,2019,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"62,924",ANZSIC06 divisions A-S (excluding classes K633...
3,2019,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,"21,505",ANZSIC06 divisions A-S (excluding classes K633...
4,2019,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,"634,710",ANZSIC06 divisions A-S (excluding classes K633...

In [32]:
df[df.Value==df.Value.max()]

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
3537,2019,Level 4,LL122,Non-Residential Property Operation,Dollars (millions),H27,Additions to fixed assets,Financial position,S,ANZSIC06 class L671200
3538,2019,Level 4,LL122,Non-Residential Property Operation,Dollars (millions),H28,Disposals of fixed assets,Financial position,S,ANZSIC06 class L671200
8172,2018,Level 4,LL122,Non-Residential Property Operation,Dollars (millions),H27,Additions to fixed assets,Financial position,S,ANZSIC06 class L671200
8173,2018,Level 4,LL122,Non-Residential Property Operation,Dollars (millions),H28,Disposals of fixed assets,Financial position,S,ANZSIC06 class L671200
12807,2017,Level 4,LL122,Non-Residential Property Operation,Dollars (millions),H27,Additions to fixed assets,Financial position,S,ANZSIC06 class L671200
12808,2017,Level 4,LL122,Non-Residential Property Operation,Dollars (millions),H28,Disposals of fixed assets,Financial position,S,ANZSIC06 class L671200
17442,2016,Level 4,LL122,Non-Residential Property Operation,Dollars (millions),H27,Additions to fixed assets,Financial position,S,ANZSIC06 class L671200
17443,2016,Level 4,LL122,Non-Residential Property Operation,Dollars (millions),H28,Disposals of fixed assets,Financial position,S,ANZSIC06 class L671200
21645,2015,Level 1,KK,Financial and Insurance Services,Dollars (millions),H26,Fixed tangible assets,Financial position,S,ANZSIC06 division K
21647,2015,Level 1,KK,Financial and Insurance Services,Dollars (millions),H28,Disposals of fixed assets,Financial position,S,ANZSIC06 division K
21679,2015,Level 3,KK11,Finance,Dollars (millions),H26,Fixed tangible assets,Financial position,S,"ANZSIC06 groups K621, K622, K623, and K624"
21681,2015,Level 3,KK11,Finance,Dollars (millions),H28,Disposals of fixed assets,Financial position,S,"ANZSIC06 groups K621, K622, K623, and K624"
21747,2015,Level 4,KK112,Financial Asset Investing,Dollars (millions),H26,Fixed tangible assets,Financial position,S,ANZSIC06 group K624
21749,2015,Level 4,KK112,Financial Asset Investing,Dollars (millions),H28,Disposals of fixed assets,Financial position,S,ANZSIC06 group K624
22077,2015,Level 4,LL122,Non-Residential Property Operation,Dollars (millions),H27,Additions to fixed assets,Financial position,S,ANZSIC06 class L671200
22078,2015,Level 4,LL122,Non-Residential Property Operation,Dollars (millions),H28,Disposals of fixed assets,Financial position,S,ANZSIC06 class L671200
31347,2013,Level 4,LL122,Non-Residential Property Operation,Dollars (millions),H27,Additions to fixed assets,Financial position,S,ANZSIC06 class L671200
31348,2013,Level 4,LL122,Non-Residential Property Operation,Dollars (millions),H28,Disposals of fixed assets,Financial position,S,ANZSIC06 class L671200